Reorder -ldl as g++9 doesn't find it
/usr/bin/ld: ../celengine/libcelengine.a(libcelengine_a-glext.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line